In [3]:
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
data=pd.read_csv("/content/drive/MyDrive/fake_job - fake_job_postings (1) (1).csv")

In [6]:
data.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [7]:
# Removing the job Id column

data.drop(['job_id'],axis=1,inplace=True)

In [8]:
data

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,Visual Designer,"US, PA, Pittsburgh",Product,NaN,Everyone has a story to tell. Everyone is uniq...,Closely work with other members of the product...,Required ExperienceMinimum 1 year of experienc...,Competitive salary commensurate with skills an...,0,1,1,Full-time,Associate,Associate Degree,Internet,Design,0
516,Brand Partner,"GB, LND,",BD,NaN,"As augmented reality jobs go, one at Blippar i...",Do you have an unquenchable entrepreneurial th...,"4+ years relevant work experience in digital, ...","Our bright, open, centrally located offices ar...",0,1,0,NaN,NaN,NaN,NaN,NaN,0
517,Web UI Engineer,"GB, , Birmingham",NaN,NaN,Friend MTS is a leading provider of technology...,The RoleWe are recruiting for a talented Web U...,Very good understanding and experience of UI d...,An understanding of concepts such as MVC or ot...,0,1,0,Full-time,NaN,NaN,Information Technology and Services,Engineering,0
518,Dairy & Farming Consultant,"US, AZ, Phoenix",Agriculture,NaN,NaN,Looking for a Consultant with experience in wo...,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,0
519,Reading Fragrance and Beauty Promotional Staff,"GB, , Reading",NaN,NaN,Established on the principles that full time e...,We are currently recruiting for an exciting Sa...,Experience in fragrance and sales.,Bonuses are available.,0,1,1,Temporary,Associate,Unspecified,Cosmetics,Sales,0

In [9]:
data[['salary_range']]

    salary_range
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
..           ...
515          NaN
516          NaN
517          NaN
518          NaN
519          NaN

[520 rows x 1 columns]

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   title                520 non-null    object
 1   location             510 non-null    object
 2   department           157 non-null    object
 3   salary_range         84 non-null     object
 4   company_profile      447 non-null    object
 5   description          520 non-null    object
 6   requirements         458 non-null    object
 7   benefits             303 non-null    object
 8   telecommuting        520 non-null    int64
 9   has_company_logo     520 non-null    int64
 10  has_questions        520 non-null    int64
 11  employment_type      440 non-null    object
 12  required_experience  324 non-null    object
 13  required_education   349 non-null    object
 14  industry             406 non-null    object
 15  function             336 non-null    object
 16  fraudulent           520 non-null    int64
dtypes: int64(4), object(13)
memory usage: 69.2+ KB

In [11]:
data

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,Visual Designer,"US, PA, Pittsburgh",Product,NaN,Everyone has a story to tell. Everyone is uniq...,Closely work with other members of the product...,Required ExperienceMinimum 1 year of experienc...,Competitive salary commensurate with skills an...,0,1,1,Full-time,Associate,Associate Degree,Internet,Design,0
516,Brand Partner,"GB, LND,",BD,NaN,"As augmented reality jobs go, one at Blippar i...",Do you have an unquenchable entrepreneurial th...,"4+ years relevant work experience in digital, ...","Our bright, open, centrally located offices ar...",0,1,0,NaN,NaN,NaN,NaN,NaN,0
517,Web UI Engineer,"GB, , Birmingham",NaN,NaN,Friend MTS is a leading provider of technology...,The RoleWe are recruiting for a talented Web U...,Very good understanding and experience of UI d...,An understanding of concepts such as MVC or ot...,0,1,0,Full-time,NaN,NaN,Information Technology and Services,Engineering,0
518,Dairy & Farming Consultant,"US, AZ, Phoenix",Agriculture,NaN,NaN,Looking for a Consultant with experience in wo...,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,0
519,Reading Fragrance and Beauty Promotional Staff,"GB, , Reading",NaN,NaN,Established on the principles that full time e...,We are currently recruiting for an exciting Sa...,Experience in fragrance and sales.,Bonuses are available.,0,1,1,Temporary,Associate,Unspecified,Cosmetics,Sales,0

In [12]:
data['salary_range'].unique()

array([nan, '20000-28000', '100000-120000', '120000-150000',
       '50000-65000', '40000-50000', '60-80', '65000-70000', '75-115',
       '75000-110000', '17000-20000', '16000-28000', '95000-115000',
       '15000-18000', '50000-70000', '45000-60000', '30000-40000',
       '70000-90000', '10000-14000', '50-110', '28000-45000', '0-34300',
       '35000-40000', '9-Dec', '44000-57000', '18500-28000',
       '55000-75000', '30000-35000', '0-0', '20000-40000',
       '360000-600000', '50000-80000', '80000-100000', '52000-78000',
       '15750-15750', '40000-65000', '45000-50000', '30000-37000',
       '45000-67000', '35000-100000', '180000-216000', '45000-65000',
       '28000-32000', '0-1000', '36000-40000', '80000-110000',
       '35000-73000', '19000-19000', '60000-120000', '120000-15000000',
       '42000-55000', '90000-120000', '100000-150000', '28000-38000',
       '1600-1700', '50000-60000', '30000-70000', '32000-40000', '50-100',
       '9000-17000', '23040-28800', '105-110'], dtype=object)

In [13]:
#data['salary_range']=data['salary_range'].fillna(32500)

In [14]:
salary_list=[np.nan,'20000-28000', '100000-120000', '120000-150000',
       '50000-65000', '40000-50000', '60-80', '65000-70000', '75-115',
       '75000-110000', '17000-20000', '16000-28000', '95000-115000',
       '15000-18000', '50000-70000', '45000-60000', '30000-40000',
       '70000-90000', '10000-14000', '50-110', '28000-45000', '0-34300',
       '35000-40000', '9-Dec', '44000-57000', '18500-28000',
       '55000-75000', '30000-35000', '0-0', '20000-40000',
       '360000-600000', '50000-80000', '80000-100000', '52000-78000',
       '15750-15750', '40000-65000', '45000-50000', '30000-37000',
       '45000-67000', '35000-100000', '180000-216000', '45000-65000',
       '28000-32000', '0-1000', '36000-40000', '80000-110000',
       '35000-73000', '19000-19000', '60000-120000', '120000-15000000',
       '42000-55000', '90000-120000', '100000-150000', '28000-38000',
       '1600-1700', '50000-60000', '30000-70000', '32000-40000', '50-100',
       '9000-17000', '23040-28800', '105-110']

In [15]:
salary_mean=[32500,(20000+28000)/2,(100000+120000)/2,(120000+150000)/2,(50000+65000)/2,(40000+50000)/2,70,67500,95,(75000+110000)/2,(17000+20000)/2,(16000+28000)/2,(95000+115000)/2,16500,60000,52500,35000,80000,12000,80,(28000+45000)/2,34300/2,37500,10,(44000+57000)/2,(18500+28000)/2,(55000+75000)/2,(30000+35000)/2,0,30000,(360000+600000)/2,65000,90000,(52000+78000)/2,15750,(40000+65000)/2,47500,33500,(45000+67000)/2,(35000+100000)/2,(180000+216000)/2,55000,30000,500,38000,95000,(35000+73000)/2,19000,90000,150000,50000,105000,125000,33000,1650,55000,50000,36000,75,13000,25000,110]

In [16]:
data['salary_range']=data['salary_range'].replace(salary_list,salary_mean)

In [17]:
data['salary_range'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
515    False
516    False
517    False
518    False
519    False
Name: salary_range, Length: 520, dtype: bool

In [18]:
data1=data.copy()

In [19]:
data1['salary_range'].dtypes

dtype('float64')

In [20]:
data1[['location']]

               location
0      US, NY, New York
1        NZ, , Auckland
2         US, IA, Wever
3    US, DC, Washington
4    US, FL, Fort Worth
..                  ...
515  US, PA, Pittsburgh
516           GB, LND,
517    GB, , Birmingham
518     US, AZ, Phoenix
519       GB, , Reading

[520 rows x 1 columns]

In [21]:
data1['location'].unique()

array(['US, NY, New York', 'NZ, , Auckland', 'US, IA, Wever',
       'US, DC, Washington', 'US, FL, Fort Worth', 'US, MD, ',
       'DE, BE, Berlin', 'US, CA, San Francisco', 'US, FL, Pensacola',
       'US, AZ, Phoenix', 'US, NJ, Jersey City', 'GB, LND, London',
       'US, CT, Stamford', 'US, FL, Orlando', 'AU, NSW, Sydney',
       'SG, 01, Singapore', 'IL, , Tel Aviv, Israel',
       'GB, SOS, Southend-on-Sea', 'US, PA, USA Northeast',
       'US, TX, Austin', 'NZ, N, Auckland', 'AE, , ', 'US, CA, Carlsbad',
       'US, NY, New York ', 'SG, , ', 'AE, AZ, Abudhabi',
       'US, MO, St. Louis', 'CA, ON, Toronto', 'US, MA, Waltham',
       'US, KS, ', 'US, WA, Everett', 'US, CA, San Ramon', 'GB, LND, ',
       'US, NY, Saint Bonaventure', 'US, NY, Yonkers', 'US, TX, HOUSTON',
       'IN, AP, Hyderabad', 'US, IL, Chicago', 'US, PA, Kutztown',
       'US, CA, Sacramento', 'US', 'US, MD, Columbia', 'US, OK, Tulsa',
       'US, NE, Omaha', 'EG, C, ', 'US, TN, Brentwood', 'US, OH, Kent',
       'US, NH, Dover', 'US, NV, Carson City', 'US, NY, New York City',
       'US, MN, St. Cloud', 'PL, , ', 'US, MN, Oronoco', 'CA, ON, Ottawa',
       'US, TX, Fort Worth', 'US, IA, Iowa city', 'US, IA, Cedar Rapids',
       'US, CT, Windsor', 'US, , ', 'GR, I, Athens',
       'US, PA, Philadelphia', 'US, OH, Cincinnati',
       'US, CA, Menlo Park, CA', 'US, NY, Otisville',
       'US, FL, Plantation', 'AE, DU, Dubai', 'US, GA, Atlanta',
       'US, PA, Scranton', 'NZ, N, Wel', 'US, CA, Anaheim',
       'GB, , Edinburgh', 'US, KY, London', 'US, NC, Charlotte',
       'US, CA, Newport Beach', 'US, MN, Minneapolis', 'US, TN, Franklin',
       'CA, ON,  Ottawa', 'GB, , ', 'US, SC, Columbia', 'GB, , Birstall',
       'GB, , London', 'US, PA, Pittsburgh', 'US, , Stocton, CA',
       'US, NC, Raleigh', 'CA, MB, Winnipeg', 'GB, WAR, Coventry',
       'US, PA, Reading', 'US, FL, Jacksonville', 'GB, , Gatwick',
       'US, TX, Dallas', 'US, IN, Indianapolis', 'US, OR, Portland',
       'GB, WLV, Kingswinford', 'US, CA, Los Angeles',
       'GB, BIR, Birmingham', 'US, IL, Melrose Park', 'US, MA, Amherst',
       'DE, BY, Wiepoldsried', 'CA, ON, Brampton', 'US, CO, Fort Collins',
       'US, FL, Boca Raton', 'US, NY, Brooklyn', 'US, GA, ',
       'US, IA, Harlan or Ames', 'US, NH, Bedford', 'GB, , Milton Keynes',
       'GB, MAN, Wigan', 'US, NV, Reno', 'GB, , Manchester',
       'US, NC, Fayetteville', 'DE, , Berlin', 'US, CA, Palo Alto',
       'IL, TA, Tel Aviv', 'US, TX, Hidalgo', nan, 'US, MA, Haverhill',
       'US, NJ, Piscataway', 'US, VA, Richmond', 'US, AL, Jacksonville',
       'US, CT, Hartford', 'US, WI, Western Wisconsin ',
       'US, MI, Detroit', 'EG, C, Cairo', 'US, MD, Baltimore',
       'US, SD, Rapid City', 'GB, CMD, London', 'AU, QLD, Brisbane',
       'US, , Newcastle', 'US, VA, Virginia Beach', 'US, UT, Draper',
       'PK, SD, Karachi', 'US, CA, Moreno Valley', 'US, TX, Houston',
       'US, , Oshkosh', 'GB, RDG, ', 'US, OH, Columbia', 'US, AR, Conway',
       'US, AR, Little Rock', 'US, CT, Wallingford', 'GR, I, Maroussi',
       'GR, E, Volos', 'US, NY, Ithaca', 'IN, MP, Indore',
       'GB, MAN, Manchester', 'US, IL, Springfield', 'BE, , Brussels',
       'US, OH, Tiffin', 'US, CA, San Mateo', 'US, ME, South Portland',
       'US, FL, Lake Mary', 'BR, RJ, Rio De Janeiro', 'CA, AB, Edmonton',
       'US, CA, Inglewood', 'US, CA, Bakersfield, CA / Mt. Poso',
       'US, MT, Bozeman', 'SA, 01, Riyadh, Olaya', 'GB, DNC, Doncaster',
       'DK, , Copenhagen', 'US, CA, Irvine', 'US, CA, Claremont',
       'GB, LIN, grimsby', 'US, MA, Cambridge', 'US, IL, Carbondale',
       'GB, LDS, Elland', 'GB, , Ossett', 'US, DC, washington',
       'US, AZ, Mesa', 'RU, MOW, Moscow', 'US, TX, Plano', 'GB, SOM, ',
       'ZA, EC, East London', 'US, IL, Schaumburg', 'GB, GBN, London',
       'US, CA, Isla Vista', 'US, MA, Boston', 'US, PA, State College',
       'US, FL, Tampa', 'US, VA, Sterling', 'US, CO, Denver',
       'GB, ESS, Chelmsford', 'US, CT, Danbury',
       'GB, , Huddersfield/Wakefield', 'US, NC, Raliegh',
       'US, CA, West Hollywood', 'GR, , ',
       'US, NJ, Newark\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t',
       'US, IL, Evanston', 'CY, 01, ', 'US, CA, Burbank',
       'US, FL, Tallahassee', "US, MO, St. Peter's", 'US, PA, Indiana',
       'US, MO, Cape Girardo', 'US, AL, Troy', 'US, NV, Las Vegas',
       'GB, ENG, London', 'US, TX, McAllen', 'US, OH, Fairfield',
       'US, OK, Oklahoma CIty', 'US, MI, East Lansing', 'DE, BY, Munich',
       'HK, , ', 'US, TX, Lubbock', 'EG, C, Cairo, Nasr City',
       'US, GA, Duluth ', 'IN, , ', 'GB, WSM, London',
       'AU, NSW, Surry Hills', 'US, SC, Charleston', 'US, VA, Reston',
       'US, IA, Dubuque', 'US, MO, Kirksville', 'TR, 34, Istanbul',
       'US, NY, NY', 'BE, BRU, Brussels', 'US, AR, Jonesboro', 'US, NY, ',
       'US, TX, ', 'GR, I, Neo Iraklio, Athens', 'CA, NT, Yellowknife',
       'US, MI, Kalamazoo', 'DE, , Germany', 'US, FL, Orlando ',
       'IE, L, Dublin', 'US, MN, St Paul', 'US, CT, Norwalk',
       'US, IL, hazelcrest', 'US, PA, Warrington', 'US, NC, Elon',
       'GB, , Southport', 'US, CA, Atherton', 'US, IN, Fishers',
       'US, CA, Newport Beach ', 'US, TX, Frisco', 'US, MN, Burnsville',
       'US, OR, Eugene', 'CA, BC, Vancouver', 'US, CA, San Diego',
       'US, OH, Athens', 'AU, VIC, Melbourne', 'IN, MP, indore',
       'DE, BE, ', 'CA, QC, Montreal', 'US, WA, Redmond',
       'US, WA, Seattle', 'LT, VL, Vilnius', 'JP, 13, Shibuya',
       'DE, BY, München', 'US, CA, Burlingame', 'US, IN, Greencastle',
       'US, NJ, East Hanover', 'US, OK, Bethany', 'US, NY, NYC',
       'US, NJ, Somerville', 'NL, , Amsterdam', 'US, TN, Spring Hill',
       'IN, MH, mumbai', 'US, IL, Gurnee', 'US, CT, Bloomfield',
       'US, MA, PITTSFIELD', 'US, CA, Riverside', 'US, MA, Wilmington',
       'GB, UKM, Stockholm, Sweden', 'US, NC, Lexington',
       'US, GA, Athens', 'AT, 5, ', 'US, CA, Redlands', 'GB, HCK, London',
       'AU, , ', 'PL, , Warsaw', 'US, NY, Albany', 'US, CA, San Carlos',
       'US, CA, San Jose', 'KR, , Seoul', 'US, WI, Wausau',
       'GB, ISL, London', 'FR, U, Aix en Provence', 'US, VA, Manassas',
       'US, OH, Dublin', 'US, IL, Crete', 'US, NY, Niagara Falls',
       'US, TX, Corpus Christi', 'US, WI, Milwaukee', 'GR, M, Heraklion',
       'US, IL, Warrenville', 'US, TX, Tyler', 'GB, , Skipton',
       'US, OH, Seven Hills', 'GR, I, ATHENS', 'ZA, , ', 'BR, , ',
       'US, CO, Englewood', 'US, MI, Macomb', 'US, MI, Ann Arbor',
       'US, DE, Wilmington', 'US, VA, Vienna', 'US, MN, Savage',
       'US, UT, Logan', 'GB, SHF, ', 'GB, , Birmingham', 'GB, , Reading'],
      dtype=object)

In [22]:
state_list=['Kerala','TamilNadu','Karnataka','Telangana','Andhra','Goa','Maharashtra','Madhyapradesh','Gujarat','Rajasthan','Punjab','Bihar','Uttarpradesh','Assam','Manipur','ArunachalPradesh','WestBengal','Mizoram','Orissa','Chattisgarh']

In [23]:
data1['location']=np.nan

In [24]:
data1['location'] = data1['location'].fillna(pd.Series(np.random.choice(state_list, size=len(data1.index))))

In [25]:
data1['location'].unique()

array(['Telangana', 'Andhra', 'Manipur', 'Rajasthan', 'Karnataka',
       'Orissa', 'Bihar', 'TamilNadu', 'Uttarpradesh', 'Madhyapradesh',
       'Punjab', 'Kerala', 'Chattisgarh', 'Gujarat', 'WestBengal',
       'ArunachalPradesh', 'Mizoram', 'Assam', 'Maharashtra', 'Goa'],
      dtype=object)

In [26]:
data1[['location']]

        location
0      Telangana
1         Andhra
2        Manipur
3      Rajasthan
4      Karnataka
..           ...
515    TamilNadu
516       Orissa
517    Rajasthan
518        Bihar
519  Chattisgarh

[520 rows x 1 columns]

In [27]:
data1['department']=np.nan

In [28]:
company_list=['ANDROIDPIT', 'Sales', 'Oil & Energy',
       'Marketplace', 'Sales and Business Development', 'Production','Playfair Capital', 'Software development',
       'Business Development', 'Financial']

In [29]:
data1['department']=data1['department'].fillna(pd.Series(np.random.choice(company_list,size=len(data1.index))))

In [30]:
data1['department'].unique()

array(['Sales and Business Development', 'Playfair Capital', 'Production',
       'ANDROIDPIT', 'Business Development', 'Financial', 'Oil & Energy',
       'Marketplace', 'Software development', 'Sales'], dtype=object)

In [31]:
data1['company_profile']=data1['company_profile'].isnull().sum()

In [32]:
data1.columns

Index(['title', 'location', 'department', 'salary_range', 'company_profile',
       'description', 'requirements', 'benefits', 'telecommuting',
       'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent'],
      dtype='object')

In [33]:
data1['company_profile']=np.nan
data1['description']=np.nan
data1['requirements']=np.nan
data1['benefits']=np.nan
data1['employment_type']=np.nan

In [34]:
cols=['company_profile','description','requirements','benefits']

In [35]:
for col in cols:
    data1[col]=data1[col].fillna(pd.Series(np.random.choice(['Yes','No'],size=len(data1.index))))

In [36]:
data1.isnull().sum()

title                    0
location                 0
department               0
salary_range             0
company_profile          0
description              0
requirements             0
benefits                 0
telecommuting            0
has_company_logo         0
has_questions            0
employment_type        520
required_experience    196
required_education     171
industry               114
function               184
fraudulent               0
dtype: int64

In [37]:
data1['employment_type'].unique()

array([nan])

In [38]:
data1['employment_type']=data1['employment_type'].fillna(pd.Series(np.random.choice(['Other','Full-time','Part-time','Contract','Temporary'],size=len(data1.index))))

In [39]:
data1.isnull().sum()

title                    0
location                 0
department               0
salary_range             0
company_profile          0
description              0
requirements             0
benefits                 0
telecommuting            0
has_company_logo         0
has_questions            0
employment_type          0
required_experience    196
required_education     171
industry               114
function               184
fraudulent               0
dtype: int64

In [40]:
data1['function'].unique()

array(['Marketing', 'Customer Service', nan, 'Sales',
       'Health Care Provider', 'Management', 'Information Technology',
       'Other', 'Engineering', 'Administrative', 'Design', 'Production',
       'Education', 'Supply Chain', 'Business Development',
       'Product Management', 'Financial Analyst', 'Consulting',
       'Human Resources', 'Project Management', 'Manufacturing',
       'Public Relations', 'Strategy/Planning', 'Advertising', 'Finance',
       'General Business', 'Research', 'Accounting/Auditing',
       'Art/Creative', 'Quality Assurance', 'Data Analyst',
       'Business Analyst', 'Writing/Editing'], dtype=object)

In [41]:
function_list=['Marketing', 'Customer Service','Sales',
       'Health Care Provider', 'Management', 'Information Technology',
       'Engineering', 'Administrative', 'Design', 'Production',
       'Education', 'Supply Chain']

experience_list=['Internship', 'Not Applicable','Mid-Senior level',
       'Associate', 'Entry level', 'Executive', 'Director']
education_list=["Bachelor's Degree", "Master's Degree",
       'High School or equivalent', 'Unspecified',
       'Some College Coursework Completed', 'Vocational', 'Certification',
       'Associate Degree', 'Professional', 'Doctorate']

industry_list=['Marketing and Advertising', 'Computer Software',
       'Hospital & Health Care', 'Online Media',
       'Information Technology and Services', 'Financial Services',
       'Management Consulting', 'Events Services', 'Internet',
       'Facilities Services', 'Consumer Electronics',
       'Telecommunications', 'Consumer Services', 'Construction',
       'Oil & Energy', 'Education Management']


employment_list=['Other','Full-time','Part-time','Contract','Temporary']

title_list=['Marketing Intern','Bill Review Manager','Accounting Clerk','Lead Guest Service Specialist','Application Developer','visual Designer','Talent Management Process Manager','Software Applications Specialist','PROJECT MANAGER','Junior HR Marketing Manager','BI Developer']

In [42]:
column1=['title','function','experience','industry','employment_type','required_education','required_experience']
for col in column1:
    data1[col]=np.nan

In [43]:
data1.isnull().sum()

title                  520
location                 0
department               0
salary_range             0
company_profile          0
description              0
requirements             0
benefits                 0
telecommuting            0
has_company_logo         0
has_questions            0
employment_type        520
required_experience    520
required_education     520
industry               520
function               520
fraudulent               0
experience             520
dtype: int64

In [44]:
data1['title']=data1['title'].fillna(pd.Series(np.random.choice(title_list,size=len(data1.index))))

data1['function']=data1['function'].fillna(pd.Series(np.random.choice(function_list,size=len(data1.index))))

data1['experience']=data1['experience'].fillna(pd.Series(np.random.choice(experience_list,size=len(data1.index))))

data1['industry']=data1['industry'].fillna(pd.Series(np.random.choice(industry_list,size=len(data1.index))))

data1['employment_type']=data1['employment_type'].fillna(pd.Series(np.random.choice(employment_list,size=len(data1.index))))

data1['required_education']=data1['required_education'].fillna(pd.Series(np.random.choice(education_list,size=len(data1.index))))

data1['required_experience']=data1['required_experience'].fillna(pd.Series(np.random.choice(experience_list,size=len(data1.index))))

In [45]:
data1['required_experience'].unique()

array(['Internship', 'Associate', 'Executive', 'Mid-Senior level',
       'Not Applicable', 'Director', 'Entry level'], dtype=object)

In [46]:
data1['required_education'].unique()

array(['Doctorate', 'Unspecified', "Master's Degree", "Bachelor's Degree",
       'Some College Coursework Completed', 'Vocational',
       'Associate Degree', 'Professional', 'Certification',
       'High School or equivalent'], dtype=object)

In [47]:
data1['industry'].unique()

array(['Consumer Electronics', 'Management Consulting',
       'Facilities Services', 'Education Management', 'Consumer Services',
       'Information Technology and Services', 'Construction',
       'Online Media', 'Financial Services', 'Hospital & Health Care',
       'Computer Software', 'Internet', 'Oil & Energy',
       'Telecommunications', 'Events Services',
       'Marketing and Advertising'], dtype=object)

In [48]:
data1.drop(['experience'],axis='columns',inplace=True)

In [49]:
#data1.drop(columns=data1.columns[-1], axis=1, inplace=True)

In [50]:
data1

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,Junior HR Marketing Manager,Telangana,Sales and Business Development,32500.0,Yes,No,Yes,Yes,0,1,0,Other,Internship,Doctorate,Consumer Electronics,Supply Chain,0
1,PROJECT MANAGER,Andhra,Playfair Capital,32500.0,No,No,Yes,No,0,1,0,Contract,Internship,Unspecified,Management Consulting,Health Care Provider,0
2,visual Designer,Manipur,Production,32500.0,No,No,Yes,No,0,1,0,Full-time,Associate,Master's Degree,Facilities Services,Education,0
3,PROJECT MANAGER,Rajasthan,ANDROIDPIT,32500.0,Yes,No,No,No,0,1,0,Contract,Executive,Doctorate,Education Management,Customer Service,0
4,Lead Guest Service Specialist,Karnataka,Business Development,32500.0,No,Yes,Yes,Yes,0,1,1,Other,Mid-Senior level,Bachelor's Degree,Consumer Services,Administrative,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,PROJECT MANAGER,TamilNadu,Oil & Energy,32500.0,No,No,Yes,No,0,1,1,Full-time,Director,High School or equivalent,Management Consulting,Education,0
516,Junior HR Marketing Manager,Orissa,ANDROIDPIT,32500.0,Yes,No,Yes,No,0,1,0,Part-time,Not Applicable,Professional,Marketing and Advertising,Engineering,0
517,Application Developer,Rajasthan,Playfair Capital,32500.0,Yes,Yes,No,No,0,1,0,Temporary,Director,Certification,Management Consulting,Marketing,0
518,Talent Management Process Manager,Bihar,Business Development,32500.0,Yes,Yes,No,Yes,0,0,0,Full-time,Executive,Certification,Consumer Electronics,Health Care Provider,0
519,Software Applications Specialist,Chattisgarh,Playfair Capital,32500.0,No,No,No,Yes,0,1,1,Contract,Not Applicable,High School or equivalent,Oil & Energy,Supply Chain,0

In [51]:
data1.isnull().sum()

title                  0
location               0
department             0
salary_range           0
company_profile        0
description            0
requirements           0
benefits               0
telecommuting          0
has_company_logo       0
has_questions          0
employment_type        0
required_experience    0
required_education     0
industry               0
function               0
fraudulent             0
dtype: int64

In [52]:
#data1.to_csv('fake_job_detect.csv', index=False)

In [53]:
data1.title.unique()

array(['Junior HR Marketing Manager', 'PROJECT MANAGER',
       'visual Designer', 'Lead Guest Service Specialist',
       'Accounting Clerk', 'Bill Review Manager', 'BI Developer',
       'Talent Management Process Manager', 'Application Developer',
       'Marketing Intern', 'Software Applications Specialist'],
      dtype=object)

In [54]:
le=LabelEncoder()

In [55]:
#Label encoding the data1
for i in data1:
    if data1[i].dtype==np.dtype('O'):
        data1[i]=le.fit_transform(data1[i])

In [56]:
data1

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,4,17,8,32500.0,1,0,1,1,0,1,0,2,4,3,2,11,0
1,7,0,5,32500.0,0,0,1,0,0,1,0,0,4,8,11,5,0
2,10,11,6,32500.0,0,0,1,0,0,1,0,1,0,5,6,3,0
3,7,15,0,32500.0,1,0,0,0,0,1,0,0,3,3,4,1,0
4,5,7,1,32500.0,0,1,1,1,0,1,1,2,5,1,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,7,16,4,32500.0,0,0,1,0,0,1,1,1,1,4,11,3,0
516,4,13,0,32500.0,1,0,1,0,0,1,0,3,6,6,12,4,0
517,1,15,5,32500.0,1,1,0,0,0,1,0,4,1,2,11,8,0
518,9,3,1,32500.0,1,1,0,1,0,0,0,1,3,2,2,5,0
519,8,4,5,32500.0,0,0,0,1,0,1,1,0,6,4,13,11,0

In [57]:
data1['salary_range'].unique()

array([3.250e+04, 2.400e+04, 1.100e+05, 1.350e+05, 5.750e+04, 4.500e+04,
       7.000e+01, 6.750e+04, 9.500e+01, 9.250e+04, 1.850e+04, 2.200e+04,
       1.050e+05, 1.650e+04, 6.000e+04, 5.250e+04, 3.500e+04, 8.000e+04,
       1.200e+04, 8.000e+01, 3.650e+04, 1.715e+04, 3.750e+04, 1.000e+01,
       5.050e+04, 2.325e+04, 6.500e+04, 0.000e+00, 3.000e+04, 4.800e+05,
       9.000e+04, 1.575e+04, 4.750e+04, 3.350e+04, 5.600e+04, 1.980e+05,
       5.500e+04, 5.000e+02, 3.800e+04, 9.500e+04, 5.400e+04, 1.900e+04,
       1.500e+05, 5.000e+04, 1.250e+05, 3.300e+04, 1.650e+03, 3.600e+04,
       7.500e+01, 1.300e+04, 2.500e+04, 1.100e+02])

In [58]:
#scaler=MinMaxScaler()

In [59]:
data1

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,4,17,8,32500.0,1,0,1,1,0,1,0,2,4,3,2,11,0
1,7,0,5,32500.0,0,0,1,0,0,1,0,0,4,8,11,5,0
2,10,11,6,32500.0,0,0,1,0,0,1,0,1,0,5,6,3,0
3,7,15,0,32500.0,1,0,0,0,0,1,0,0,3,3,4,1,0
4,5,7,1,32500.0,0,1,1,1,0,1,1,2,5,1,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,7,16,4,32500.0,0,0,1,0,0,1,1,1,1,4,11,3,0
516,4,13,0,32500.0,1,0,1,0,0,1,0,3,6,6,12,4,0
517,1,15,5,32500.0,1,1,0,0,0,1,0,4,1,2,11,8,0
518,9,3,1,32500.0,1,1,0,1,0,0,0,1,3,2,2,5,0
519,8,4,5,32500.0,0,0,0,1,0,1,1,0,6,4,13,11,0

In [60]:
data1

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,4,17,8,32500.0,1,0,1,1,0,1,0,2,4,3,2,11,0
1,7,0,5,32500.0,0,0,1,0,0,1,0,0,4,8,11,5,0
2,10,11,6,32500.0,0,0,1,0,0,1,0,1,0,5,6,3,0
3,7,15,0,32500.0,1,0,0,0,0,1,0,0,3,3,4,1,0
4,5,7,1,32500.0,0,1,1,1,0,1,1,2,5,1,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,7,16,4,32500.0,0,0,1,0,0,1,1,1,1,4,11,3,0
516,4,13,0,32500.0,1,0,1,0,0,1,0,3,6,6,12,4,0
517,1,15,5,32500.0,1,1,0,0,0,1,0,4,1,2,11,8,0
518,9,3,1,32500.0,1,1,0,1,0,0,0,1,3,2,2,5,0
519,8,4,5,32500.0,0,0,0,1,0,1,1,0,6,4,13,11,0

In [61]:
data1.to_csv('cleaned.csv')